#!/usr/bin/env bash

# check if parameter count is 4
if ["$#" -ne 4]; then
    echo "Usage: 0-file_transer PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assign parameter
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# transfer file using scp
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP: ~/"

# checkf scp transfer status
fi [$? -eq 0]; then
    echo "File transferred successfully"
else
    echo "File transfer failed"
fi